### ISSUE TITLE
apps/lwaftr/fragmentv4.lua:152: invalid order function for sorting

### ISSUE THREAD

**Issue by mwiget** [Igalia/snabb#290] opened 2016-03-21 15:55 UTC
Sending a generated (though good) pcap file with IPv4 fragments of large packets over and over into lwaftr running a huge binding table of 4M entries, lwaftr terminates with the following error message:

```
~/item-19-fragmentation/igalia$ sudo snabbswitch/src/snabb lwaftr run --conf abbvmx-lwaftr-xe0.conf --v4-pci 0000:05:00.0 --v6-pci 0000:05:00.1 -v
loading compiled binding table from ./snabbvmx-lwaftr.binding.o
compiled binding table ./snabbvmx-lwaftr.binding.o is out of date; recompiling.
loading source binding table from ./snabbvmx-lwaftr.binding
Time (s),IPv4 RX MPPS,IPv4 RX Gbps,IPv4 TX MPPS,IPv4 TX Gbps,IPv6 RX MPPS,IPv6 RX Gbps,IPv6 TX MPPS,IPv6 TX Gbps
0.999564,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
apps/lwaftr/fragmentv4.lua:152: invalid order function for sorting
stack traceback:
    core/main.lua:124: in function <core/main.lua:122>
    [C]: in function 'sort'
    apps/lwaftr/fragmentv4.lua:152: in function 'reassemble'
    apps/lwaftr/ipv4_apps.lua:90: in function 'method'
    core/app.lua:79: in function 'with_restart'
    core/app.lua:313: in function 'thunk'
    core/histogram.lua:135: in function 'breathe'
    core/app.lua:251: in function 'main'
    program/lwaftr/run/run.lua:146: in function 'run'
    program/lwaftr/lwaftr.lua:17: in function 'run'
    core/main.lua:43: in function <core/main.lua:34>
    [C]: in function 'xpcall'
    core/main.lua:153: in main chunk
    [C]: at 0x0044fcb0
    [C]: in function 'pcall'
    core/startup.lua:3: in main chunk
    [C]: in function 'require'
    [string "require "core.startup""]:1: in main chunk
```

The content of the lwaftr conf file snabbvmx-lwaftr-xe0.conf:

```
$ cat snabbvmx-lwaftr-xe0.conf
vlan_tagging = false,
binding_table = snabbvmx-lwaftr.binding,
aftr_ipv6_ip = 2a02:587:f700::100,
aftr_mac_inet_side = 5c:45:27:15:a0:0d,
inet_mac = 44:44:44:44:44:44,
ipv6_mtu = 9500,
policy_icmpv6_incoming = DROP,
policy_icmpv6_outgoing = DROP,
icmpv6_rate_limiter_n_packets = 6e5,
icmpv6_rate_limiter_n_seconds = 2,
aftr_ipv4_ip = 192.168.4.2,
aftr_mac_b4_side = 5c:45:27:15:a0:0d,
next_hop6_mac = 66:66:66:66:66:66,
ipv4_mtu = 9500,
policy_icmpv4_incoming = DROP,
policy_icmpv4_outgoing = DROP,
```

The pcap file (attached) is sent with tcpreplay over a connected 10GE port:

```
sudo  tcpreplay --preload-pcap -i p1p1 -t -K -l 10000 v4-frag.pcap
```

The error typically appears in seconds on my dev branch, but also happened a minute or two using the latest branch 'next' from https://github.com/SnabbCo/snabbswitch.git. 

Whats interesting though is that all the files in apps/lwaftr/ are identical, so changes in snabb core must account for the delta of time it takes to produce the error, though the error is the same. 

Its well possible, that adding hardening will solve this. When first discovered with snabbvmx, I do see the counters lwaftr_v4 reassemble_invalid increasing, though slowly, with a crash once seen at

```
 lwaftr_v4 reassemble_invalid                     32                    0
```

That counter gets incremented in function Reassembler:push() in ipv4_apps.lua when

```
...
 elseif status == fragmentv4.REASSEMBLE_INVALID then
            self:clean_fragment_cache(frags)
            counter.add(reassemble_invalid)
            if maybe_pkt then -- This is an ICMP packet
               transmit(errors, maybe_pkt)
            end
         else -- unreachable
            packet.free(pkt)
...
```

To show the version used of snabb:

```
$ git status
On branch next
Your branch is up-to-date with 'origin/next'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    .AppleDouble/
    lib/luajit/usr/

nothing added to commit but untracked files present (use "git add" to track)
mwiget@st:~/item-19-fragmentation/igalia/snabbswitch$ git remote -v
origin  https://github.com/SnabbCo/snabbswitch.git (fetch)
origin  https://github.com/SnabbCo/snabbswitch.git (push)

$ git log -1
commit b388a636ceb45875e508d047c6cd7b94e19dec74
Merge: 7a5c2f2 75604d3
Author: Luke Gorrie <luke@snabb.co>
Date:   Mon Mar 21 10:01:46 2016 +0000

    Merge #831 remote-tracking branch 'domenkozar/nix' into next

    Added note to branches.md that branch 'nix' feeds upstream to
    'kbara-next' following ack from kbara on #835.
```

Supporting (and gzipped) files to reproduce the issue:

[snabbvmx-lwaftr.binding.gz](https://github.com/Igalia/snabbswitch/files/182566/snabbvmx-lwaftr.binding.gz)

[v4-frag.pcap.gz](https://github.com/Igalia/snabbswitch/files/182563/v4-frag.pcap.gz)

**Comment by wingo** [comment] 2016-03-22 09:55
Is the lwaftr dropping packets on ingress?  In that case the reassembly buffer could keep growing.  That would explain the rising invalid reassembly counter.

I am not sure what to do with this TBH; the reassembly function looks good, the only thing that to my mind that would cause this would be some sort of memory corruption possibly triggered by overflow, or a bug in LuaJIT.  I don't like not being able to answer this question well though :/  The reassembly rewrite that we have discussed would fix this issue, but that's not a very nice answer :/

**Comment by mwiget** [comment] 2016-03-22 14:00
I'm also guessing that its related to ingress packet drops, though didn't check for it. But the pcap file is fine and it works when sending the packets at lower speed. The real fix really will be some hardening on the reassembly function. Its ok for me to just keep this one open and come back to it once some hardening is added. I used this as a test case as well on what to document and how. I'm sure I'll be looking back at this issue report many times down the road.

**Comment by dpino** [comment] 2016-10-18 10:42
I was trying to reproduce it but I cannot. The issue is that there's no "tcpdump" in NixOS. I used "packetblaster replay" instead, but it finishes with a crash after a while (the .pcap file is too big, more than 5e5 packets):

```
core/packet.lua:139: packet allocation overflow
stack traceback:
        core/main.lua:128: in function <core/main.lua:126>
        [C]: in function 'assert'
        core/packet.lua:139: in function 'preallocate_step'
        core/packet.lua:62: in function 'allocate'
        core/packet.lua:114: in function 'from_string'
        apps/pcap/pcap.lua:25: in function 'method'
        core/app.lua:79: in function 'with_restart'
        core/app.lua:297: in function 'thunk'
        core/histogram.lua:135: in function 'breathe'
        core/app.lua:251: in function 'main'
        program/packetblaster/packetblaster.lua:47: in function 'run_loadgen'
        program/packetblaster/replay/replay.lua:39: in function 'run'
        program/packetblaster/packetblaster.lua:61: in function 'run'
```

I tried with a much smaller file, and it works. Would be interesting to know if the issue still applies.

**Comment by kbara** [comment] 2016-10-18 10:54
I'd be surprised if it did, given that I hardened (and completely rewrote) reassembly, but if it did, that would certainly be very important.

**Comment by teknico** [comment] 2016-10-18 11:02
@dpino, `tcpdump` is packaged in NixOS, here's the definition: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/tcpdump/default.nix

**Comment by dpino** [comment] 2016-10-19 08:38
@teknico Sorry, I meant "tcpreplay". Do you know if it's available in NixOS? I cannot find it with "nox" or "nix-env".

**Comment by teknico** [comment] 2016-10-19 08:59
@dpino, no, I cannot find it on http://nixos.org/nixos/packages.html either.

**Comment by dpino** [comment] 2017-03-29 22:32
I'm closing this issue as it seems no longer valid.

I managed to install `tcpreplay` in our working environment and run the test case. I used tip of `lwaftr-snabbvmx` branch.

```
$ git log -1
commit df96a4b9a0c11e5be6d725effa8ad6640146b237
Merge: 5c26a61 a33ec61
Author: Diego Pino <dpino@users.noreply.github.com>
Date:   Wed Mar 8 14:15:19 2017 +0100

    Merge pull request #704 from dpino/issue-476
    
    nh_fwd cache refresh packets need entropy
```

I run the lwAFTR for more than 5 minutes, feeding traffic from tcpreplay in the v4 interface. Packets matched the softwires and got encapsulated. Performance was not good, but that's due to the speed `tcpreplay` can work on Linux interfaces I think. Here are the results:

```
$ sudo tcpreplay -i enp2s0f0 t -K -l 10000 v4-frag.pcap
```

```
$ sudo ./snabb lwaftr run --conf snabbvmx-lwaftr-xe0.conf --v4 82:00.0 --v6 82:00.1 -v
300.999242,0.001063,0.009341,0.000000,0.000000,0.000000,0.000000,0.000792,0.009398
301.999240,0.001065,0.009343,0.000000,0.000000,0.000000,0.000000,0.000804,0.009541
302.999242,0.001072,0.009412,0.000000,0.000000,0.000000,0.000000,0.000804,0.009541
303.999239,0.000457,0.004014,0.000000,0.000000,0.000000,0.000000,0.000342,0.004058
304.999239,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
```

**Closed by dpino** 2017-03-29 22:32 UTC
